### PR TITLE
Create `platform.mk` for platform-specific build configuation

### PR DESCRIPTION
**Pull request by johnsonjh**
Apply some heuristics to determine (without the need for user interaction) a build configuration to compile optimally by just invoking `make`, and all without interfering with cross-compiled builds.

This also (*portably*) silences any `lto-wrapper` LTRANS warnings.

This is done automatically and using only GNU Make and POSIX-conforming shell utilities (`printf`, `uname`, and `grep`).

- Determine if `CC` is *Clang* or *GCC* (by checking the output of “`--version`”, and if it is, use extra warning flags, defined in “`EXTRA_CFLAGS`”.

- Determines if “`-flto=auto`” is invalid, and if so, assumes “`-flto`” should be used instead. \
\
This is done by invoking the compiler frontend in preprocessor mode and passing the flag.  This is not foolproof, but it is fast, and it doesn't require compiling any actual code and handling the output.

  - If `CC` contains “`icc`" (*Intel C Compiler Classic*), enable IPO.

  - If `CC` contains "`suncc`" (*Oracle Developer Studio*), "`nvc`" (*NVIDIA HPC SDK*), or "`xlc`" (*IBM XL C/C++ <=16*), disable LTO.

  - Disables LTO when using *GCC* on *IBM AIX* or *IBM OS/400*.

  - Always use "`-flto`" for LTO on *Solaris* or *illumos* systems.

---

This is a draft while I do some more testing.  Also, if you decide to take any of the other changes in pending PRs, this will likely need to be rebased anyway.

### CODE REVIEW

**Comment by dmsc** [comment]
Seems a little convoluted, but if it works I'm ok with this.

**Comment by johnsonjh** [comment]
> Seems a little convoluted, but if it works I'm ok with this.

I use something similar in another project… The only fundamental change that might be worthwhile is to try also passing “-flto” via the preprocessor and if that also fails, disabling it altogether.  However, as it is now, it attempts “-flto=auto” and falls back to “-flto”, which is exactly the way you had the Makefile to start with.  And then after that, adjust for some known OS and compiler strangeness.  

I think I’ll just leave it alone, because even in the worst case, where everything goes wrong, it’ll default back to “-flto” as it originally was.

The only change I think I’ll make is respecting a “NO_LTO” variable that can be set.

**Comment by johnsonjh** [comment]
I’m going to think about this another day or so …

**Comment by johnsonjh** [comment]
I will still do this, but a different way.  Closing for now.

**Pull request closed without merging**
